// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyHX_Uygccqr4I_S_Jd0FCG8mcOnXdo4o',
    appId: '1:804074582835:web:43dcd54dcbe265ce45c446',
    messagingSenderId: '804074582835',
    projectId: 'my-flutter-projects-9441b',
    authDomain: 'my-flutter-projects-9441b.firebaseapp.com',
    storageBucket: 'my-flutter-projects-9441b.firebasestorage.app',
    measurementId: 'G-CXF9FJJZ6F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23PU5hkG6K5o2MBpMCSi45SN_IgHUEUw',
    appId: '1:804074582835:ios:f8e3e7c51b1abee345c446',
    messagingSenderId: '804074582835',
    projectId: 'my-flutter-projects-9441b',
    storageBucket: 'my-flutter-projects-9441b.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23PU5hkG6K5o2MBpMCSi45SN_IgHUEUw',
    appId: '1:804074582835:ios:f8e3e7c51b1abee345c446',
    messagingSenderId: '804074582835',
    projectId: 'my-flutter-projects-9441b',
    storageBucket: 'my-flutter-projects-9441b.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyHX_Uygccqr4I_S_Jd0FCG8mcOnXdo4o',
    appId: '1:804074582835:web:780db7ac1f17a7bf45c446',
    messagingSenderId: '804074582835',
    projectId: 'my-flutter-projects-9441b',
    authDomain: 'my-flutter-projects-9441b.firebaseapp.com',
    storageBucket: 'my-flutter-projects-9441b.firebasestorage.app',
    measurementId: 'G-406M23513B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24HsKPutOoQOoDRS41BnhdvKa2H5cLks',
    appId: '1:804074582835:android:cd78ebd076c7b9be45c446',
    messagingSenderId: '804074582835',
    projectId: 'my-flutter-projects-9441b',
    storageBucket: 'my-flutter-projects-9441b.firebasestorage.app',
  );

}